/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mylibsys.libsystem.ui.UIND;

import com.mylibsys.libsystem.dao.UserDao;
import com.mylibsys.libsystem.ui.UIND.phieuMuonChiTietNdUi;
import static com.mylibsys.libsystem.dao.UserDao.maTk;

import com.mylibsys.libsystem.dao.phieuMuonDao;
import com.mylibsys.libsystem.entity.phieuMuon;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kuteb
 */
public class phieuMuonNdUi extends javax.swing.JPanel {

    UserDao usd = new UserDao();
    private DefaultTableModel tblModel;
    JFrame jf1;

    /**
     * Creates new form phieuMuonNdUi
     */
    public phieuMuonNdUi() {
        initComponents();
        if (maTk == null) {
            maTk = usd.getMaTKByGMail();
        }
        inittables();
        fillDataTable();
        lblPM.requestFocus();
        txtTim.setText("Nhập Mã Phiếu Mượn Để Tìm");
    }

    public void inittables() {
        tblModel = new DefaultTableModel();
        String[] colum = new String[]{"Mã Phiếu Mượn", "Mã Người Dùng", "Ngày Mượn", "Ngày Đến Hạn"};
        tblModel.setColumnIdentifiers(colum);
        tblPhieuMuonND.setModel(tblModel);
    }
//    List<phieuMuon> list = new ArrayList<>();

    public void fillDataTable() {
//        list = new phieuMuonDao().selectBySql();
        System.out.println(maTk);
        for (phieuMuon pm : new phieuMuonDao().selectByMaTk(maTk)) {
            tblModel.addRow(new String[]{pm.getMaPM(), pm.getMaND(), pm.getNgayDenHan(), pm.getNgayMuon()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPM = new javax.swing.JLabel();
        borderApp1 = new com.mylibsys.libsystem.ui.borderApp();
        txtTim = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPhieuMuonND = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMand = new javax.swing.JTextField();
        txtMaPm = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dateMuon = new com.toedter.calendar.JDateChooser();
        dateHan = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(850, 550));
        setMinimumSize(new java.awt.Dimension(850, 550));
        setPreferredSize(new java.awt.Dimension(850, 550));

        lblPM.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPM.setText("Phiếu Mượn");

        borderApp1.setBackground(new java.awt.Color(0, 204, 204));

        txtTim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTimFocusLost(evt);
            }
        });

        btnTim.setBackground(new java.awt.Color(254, 231, 197));
        btnTim.setText("TÌm Kiếm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout borderApp1Layout = new javax.swing.GroupLayout(borderApp1);
        borderApp1.setLayout(borderApp1Layout);
        borderApp1Layout.setHorizontalGroup(
            borderApp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borderApp1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTim)
                .addContainerGap())
        );
        borderApp1Layout.setVerticalGroup(
            borderApp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borderApp1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(borderApp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblPhieuMuonND.setBackground(new java.awt.Color(0, 204, 204));
        tblPhieuMuonND.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPhieuMuonND.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblPhieuMuonNDMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblPhieuMuonND);

        jLabel1.setText("Mã Phiếu Mượn :");

        jLabel3.setText("Mã Người Dùng :");

        jLabel4.setText("Ngày Mượn :");

        dateMuon.setDateFormatString("dd-MM-yyyy");

        dateHan.setDateFormatString("dd-MM-yyyy");

        jLabel5.setText("Ngày Đến Hạn: ");

        jButton1.setBackground(new java.awt.Color(255, 204, 153));
        jButton1.setText("Tra cứu PMCT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(385, 385, 385)
                                .addComponent(jLabel4)
                                .addGap(21, 21, 21))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMaPm)
                                    .addComponent(txtMand, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateHan, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(borderApp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(lblPM)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPM, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(borderApp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMaPm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(dateMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateHan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtMand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)))
                        .addGap(37, 37, 37)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed

    }//GEN-LAST:event_btnTimActionPerformed

    private void tblPhieuMuonNDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhieuMuonNDMousePressed
        int a = tblPhieuMuonND.getSelectedRow();
//        System.out.println(a);
        txtMaPm.setText((String) tblModel.getValueAt(a, 0));
        txtMand.setText((String) tblModel.getValueAt(a, 1));
        dateMuon.setDate(parseStringToDate((String) tblModel.getValueAt(a, 2)));
        dateHan.setDate(parseStringToDate((String) tblModel.getValueAt(a, 3)));

    }//GEN-LAST:event_tblPhieuMuonNDMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        phieuMuonChiTietNdUi pmnd = new phieuMuonChiTietNdUi();
        pmnd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        pmnd.setVisible(true);

//JPanel jp = new phieuMuonChiTietNdUi();
//        if (jf1 == null) {
//            jf1 = new JFrame();
//            jf1.setSize(760, 480);
//            jf1.add(jp);
//            jf1.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
//            jf1.setResizable(false);
//            jf1.setVisible(true);
//        } else {
//            jf1.setVisible(true);
//        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtTimFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimFocusGained
        if (txtTim.getText().equals("") || txtTim.getText().equals("Nhập Mã Phiếu Mượn Để Tìm")) {
            txtTim.setText("");

        }
    }//GEN-LAST:event_txtTimFocusGained

    private void txtTimFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimFocusLost
        if (txtTim.getText().equals("")) {
            txtTim.setText("Nhập Mã Phiếu Mượn Để Tìm");

        }
    }//GEN-LAST:event_txtTimFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mylibsys.libsystem.ui.borderApp borderApp1;
    private javax.swing.JButton btnTim;
    private com.toedter.calendar.JDateChooser dateHan;
    private com.toedter.calendar.JDateChooser dateMuon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPM;
    private javax.swing.JTable tblPhieuMuonND;
    private javax.swing.JTextField txtMaPm;
    private javax.swing.JTextField txtMand;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables

    public Date parseStringToDate(String dateString) {
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        try {
            Date date = formatter.parse(dateString);
            return date;
        } catch (ParseException e) {
//            System.out.println("ParseException: " + e.getMessage());
            return null;
        }
    }

}
