/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mylibsys.libsystem.ui.UIND;

import com.mylibsys.libsystem.dao.UserDao;
import static com.mylibsys.libsystem.dao.UserDao.maTk;
import com.mylibsys.libsystem.dao.phieuMuonCTDao;
import com.mylibsys.libsystem.dao.phieuTraDao;
import com.mylibsys.libsystem.entity.phieuMuonChiTiet;
import com.mylibsys.libsystem.entity.phieuTra;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kuteb
 */
public class phieuTraNdUi extends javax.swing.JPanel {

    phieuTraDao pt = new phieuTraDao();
    DefaultTableModel tblModel;
    UserDao usd = new UserDao();

    /**
     * Creates new form phieuTraNdUi
     */
    public phieuTraNdUi() {

        initComponents();
        if (maTk == null) {
            maTk = usd.getMaTKByGMail();
        }
        inittables();
        fillDataTable();
        fillCbb();
        lblPT.requestFocus();
        txtTim.setText("Nhập Mã Phiếu Trả Để Tìm");
    }

    public void inittables() {
        tblModel = new DefaultTableModel();
        String[] colum = new String[]{"Mã Phiếu Trả", "Mã PMCT", "Ngày Trả", "Tiền Phạt", "Ghi Chú"};
        tblModel.setColumnIdentifiers(colum);
        tblPhieuTra.setModel(tblModel);
    }

    public void fillDataTable() {
        List<phieuTra> list = new phieuTraDao().selectAllByND(maTk);
        System.out.println(list.size());
        for (phieuTra pt1 : list) {
            tblModel.addRow(new String[]{pt1.getMaPhieuTra(), pt1.getMaPmct(), pt1.getNgayTra(), String.valueOf(pt1.getTienPhat()), pt1.getGhiChu()});
        }
    }

    public void fillCbb() {
        for (phieuMuonChiTiet pm : new phieuMuonCTDao().selectBySql()) {
            cbbPMCT.addItem(pm.getMaPmct());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPT = new javax.swing.JLabel();
        borderApp1 = new com.mylibsys.libsystem.ui.borderApp();
        txtTim = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhieuTra = new javax.swing.JTable();
        cbbPMCT = new javax.swing.JComboBox<>();
        dateTra = new com.toedter.calendar.JDateChooser();
        txtSoNgayMuon = new javax.swing.JTextField();
        txtTienPhat = new javax.swing.JTextField();
        txtSoSachDaMUon = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaPT = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(850, 550));
        setMinimumSize(new java.awt.Dimension(850, 550));

        lblPT.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPT.setText("Phiếu Trả");

        borderApp1.setBackground(new java.awt.Color(0, 204, 204));

        txtTim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTimFocusLost(evt);
            }
        });
        txtTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimActionPerformed(evt);
            }
        });

        btnTim.setBackground(new java.awt.Color(254, 231, 197));
        btnTim.setText("TÌm Kiếm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout borderApp1Layout = new javax.swing.GroupLayout(borderApp1);
        borderApp1.setLayout(borderApp1Layout);
        borderApp1Layout.setHorizontalGroup(
            borderApp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borderApp1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        borderApp1Layout.setVerticalGroup(
            borderApp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borderApp1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(borderApp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblPhieuTra.setBackground(new java.awt.Color(0, 204, 204));
        tblPhieuTra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPhieuTra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblPhieuTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblPhieuTraMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblPhieuTra);

        cbbPMCT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn PMCT" }));

        dateTra.setDateFormatString("dd-MM-yyyy");

        txtSoNgayMuon.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtSoNgayMuon.setText("Số Ngày Mượn");
        txtSoNgayMuon.setEnabled(false);

        txtTienPhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienPhatActionPerformed(evt);
            }
        });

        txtSoSachDaMUon.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtSoSachDaMUon.setText("Số Lượng Sách Được Mượn Theo PMCT");
        txtSoSachDaMUon.setEnabled(false);

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        jScrollPane2.setViewportView(txtGhiChu);

        jLabel8.setText("Ghi Chú :");

        jLabel1.setText("Số Lượng sách đã mượn :");

        jLabel3.setText("TIền Phạt :");

        jLabel5.setText("Số Ngày Mượn :");

        jLabel4.setText("Ngày Trả :");

        jLabel7.setText("Mã Phiếu Mượn Chi Tiết :");

        jLabel6.setText("Mã Phiếu Trả :");

        txtMaPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaPTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSoNgayMuon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateTra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbPMCT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTienPhat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoSachDaMUon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaPT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPT)
                .addGap(364, 364, 364))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(borderApp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(borderApp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dateTra, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbbPMCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTienPhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoSachDaMUon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addComponent(jLabel7))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        if ("".equals(txtTim.getText())) {
            JOptionPane.showMessageDialog(this, "ô tìm kiếm đang trống");
            return;
        }
        if (timKiem() != null) {
            JOptionPane.showMessageDialog(this, "Đã tìm thấy");
        } else {
            JOptionPane.showMessageDialog(this, "Không tồn tại");

        }
    }//GEN-LAST:event_btnTimActionPerformed

    private void tblPhieuTraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhieuTraMousePressed
        int a = tblPhieuTra.getSelectedRow();

        SimpleDateFormat formatter1 = new SimpleDateFormat("dd-MM-yyyy"); // định dạng của ngày tháng
        String dateString1 = (String) tblModel.getValueAt(a, 2); // lấy giá trị trả về từ bảng ở dòng thứ a, cột thứ 4
        Date date1 = null;
        try {
            date1 = formatter1.parse(dateString1); // chuyển đổi chuỗi thành đối tượng Date
        } catch (ParseException e) {
            e.printStackTrace();
        }
        dateTra.setDate(date1);
        updateUI();
        Date selectedDate = dateTra.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String formattedDate = dateFormat.format(selectedDate);
        txtMaPT.setText((String) tblModel.getValueAt(a, 0));
        cbbPMCT.setSelectedItem((String) tblModel.getValueAt(a, 1));
        txtTienPhat.setText((String) tblModel.getValueAt(a, 3));
        txtGhiChu.setText((String) tblModel.getValueAt(a, 4));
        txtSoNgayMuon.setText(String.valueOf(pt.soNgayMuon((String) cbbPMCT.getSelectedItem(), formattedDate)));
        txtSoSachDaMUon.setText(String.valueOf(pt.soLuong((String) cbbPMCT.getSelectedItem())));
    }//GEN-LAST:event_tblPhieuTraMousePressed

    private void txtTienPhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienPhatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienPhatActionPerformed

    private void txtMaPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaPTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaPTActionPerformed

    private void txtTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimActionPerformed

    private void txtTimFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimFocusGained
        if (txtTim.getText().equals("") || txtTim.getText().equals("Nhập Mã Phiếu Trả Để Tìm")) {
            txtTim.setText("");

        }
    }//GEN-LAST:event_txtTimFocusGained

    private void txtTimFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimFocusLost
        if (txtTim.getText().equals("")) {
            txtTim.setText("Nhập Mã Phiếu Trả Để Tìm");

        }
    }//GEN-LAST:event_txtTimFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mylibsys.libsystem.ui.borderApp borderApp1;
    private javax.swing.JButton btnTim;
    private javax.swing.JComboBox<String> cbbPMCT;
    private com.toedter.calendar.JDateChooser dateTra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPT;
    private javax.swing.JTable tblPhieuTra;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtMaPT;
    private javax.swing.JTextField txtSoNgayMuon;
    private javax.swing.JTextField txtSoSachDaMUon;
    private javax.swing.JTextField txtTienPhat;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables
public phieuTra timKiem() {
        for (phieuTra ptraS : pt.selectAllByND(maTk)) {
            if (txtTim.getText().equalsIgnoreCase(ptraS.getMaPhieuTra())) {
                txtMaPT.setText(ptraS.getMaPhieuTra());
                cbbPMCT.setSelectedItem(ptraS.getMaPmct());
                txtGhiChu.setText(ptraS.getGhiChu());
                txtMaPT.setText(ptraS.getMaPhieuTra());
                dateTra.setDate(parseStringToDate(ptraS.getNgayTra()));
                txtSoNgayMuon.setText(String.valueOf(pt.soNgayMuon((String) cbbPMCT.getSelectedItem(), parseDateEnd(ptraS.getNgayTra()))));
                txtTienPhat.setText(String.valueOf((ptraS.getTienPhat())));
                return ptraS;
            }

        }

        return null;
    }

    public Date parseStringToDate(String dateString) {
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        try {
            Date date = formatter.parse(dateString);
            return date;
        } catch (ParseException e) {
            return null;
        }
    }

    public String parseDateEnd(String date) {
        SimpleDateFormat inputFormat = new SimpleDateFormat("dd-MM-yyyy");
        SimpleDateFormat outputFormat = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Date parsedDate = inputFormat.parse(date);
            String outputDate = outputFormat.format(parsedDate);
            return outputDate;
        } catch (ParseException e) {
//            System.out.println("ParseException: " + e.getMessage());
            return null;
        }
    }
}
