/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mylibsys.libsystem.ui;

import com.mylibsys.libsystem.dao.DangKiNDDAO;

import com.mylibsys.libsystem.entity.NguoiDung;

import com.mylibsys.libsystem.entity.User;
import com.mylibsys.libsystem.utils.DateTimeRanDomID;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Properties;
import java.util.Random;
import javax.swing.JOptionPane;
import java.util.Properties;
import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.Timer;

/**
 *
 * @author Mr. Dung
 */
public class DkUi extends javax.swing.JFrame  {

    private int randomNumber;
    private Timer timer;
    private int remainingSeconds;
    DangKiNDDAO dkDAO = new DangKiNDDAO();
    
       private Thread numberThread;
    private boolean isRunning = false;

    /**
     * Creates new form DkUi
     */
    public DkUi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtMaXacNhan = new javax.swing.JTextField();
        btnGuiMa = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnDangKi = new javax.swing.JButton();
        txtThoiGian = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        txtUser = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Mã xác nhận");

        btnGuiMa.setText("Gửi mã");
        btnGuiMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiMaActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnDangKi.setText("Đăng Ký");
        btnDangKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKiActionPerformed(evt);
            }
        });

        txtThoiGian.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtThoiGian.setForeground(new java.awt.Color(255, 0, 51));
        txtThoiGian.setText("Mã xác nhận có hiệu lực trong 30s");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setText("ĐĂNG KÝ TÀI KHOẢN ADMIN");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Họ Tên :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("SDT :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Địa Chỉ :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Email :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Password :");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Username :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtHoTen)
                                    .addComponent(txtSDT)
                                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(23, 23, 23))
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtUser)
                                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(304, 304, 304))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(btnDangKi, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMaXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnGuiMa))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(txtThoiGian)))))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMaXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuiMa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtThoiGian)
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDangKi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuiMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiMaActionPerformed
        // TODO add your handling code here:

        if (validateMaXN()) {
            if (numberThread != null && isRunning == true) {
                numberThread.interrupt();
                isRunning = false;
            }
            if (!isRunning) {
                startNumberThread();
                startCountDown();
                GuiMail();
            }
        }
    }//GEN-LAST:event_btnGuiMaActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnDangKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKiActionPerformed
        // TODO add your handling code here:
        if (validateForm()) {
//            if (dkDAO.findbyMaTK(txtMaTk.getText()) != null ) {
//                JOptionPane.showMessageDialog(this, "Ma tai khoan da ton tai!");
//                return;
//            }
            if (dkDAO.findbyUserName(txtUser.getText()) != null) {
                JOptionPane.showMessageDialog(this, "Ma nguoi dung da ton tai!");
                return;
            }
            
            if (dkDAO.findbyEmail(txtEmail.getText()) != null) {
                JOptionPane.showMessageDialog(this, "Email nguoi dung da ton tai!");
                return;
            }
            
            try {
                DateTimeRanDomID dt = new DateTimeRanDomID();
                dt.generateUniqueRandomCode();
                String maND = "ND" + dt.generateUniqueRandomCode();
                String maTK = "TK" + dt.generateUniqueRandomCode();
                User us = getModelTK(maTK);
                NguoiDung nd = getModelND(maND, maTK);
                if (dkDAO.addTKAdmin(us) > 0 && dkDAO.addND(nd) > 0) {
                    JOptionPane.showMessageDialog(this, "Đăng kí thành công!");
//                     btnGuiMa.setEnabled(true);
                    remainingSeconds = -1;
               
                    LoginUI lg = new LoginUI();
                    lg.setVisible(true);
                    this.dispose();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnDangKiActionPerformed
//mycode

    public void reset() {
//        txtMaTk.setText("");
        txtUser.setText("");
        txtPass.setText("");
        txtEmail.setText("");
//        txtMaAD.setText("");
        txtHoTen.setText("");
        txtSDT.setText("");
        txtDiaChi.setText("");
        txtMaXacNhan.setText("");
    }

    public NguoiDung getModelND(String maND, String maTK) {

        NguoiDung nd = new NguoiDung();
        nd.setMaND(maND);
        nd.setTenND(txtHoTen.getText());
        nd.setSdt(txtSDT.getText());
        nd.setEmail(txtEmail.getText());
        nd.setDiaChi(txtDiaChi.getText());
        nd.setMaTK(maTK);
        return nd;
    }

    public User getModelTK(String maTK) {
        User us = new User();
        us.setMaTk(maTK);
        char[] passwordChars = txtPass.getPassword();
        String password = new String(passwordChars);
        us.setPassword(password);
        us.setUsername(txtUser.getText());
        return us;
    }

//    private void RandomNumber() {
//        Random random = new Random();
//
//        while (true) {
//            // Tạo số ngẫu nhiên từ 1 đến 100 (bạn có thể thay đổi khoảng số tùy ý)
//            randomNumber = random.nextInt(900000) + 100000;
//            System.out.println("Số ngẫu nhiên: " + randomNumber);
//
//            // Ngủ trong 1 phút (1 * 60 * 1000 milliseconds) trước khi tạo số tiếp theo
//            try {
//                Thread.sleep(1 * 60 * 1000);
//            } catch (InterruptedException e) {
//                e.printStackTrace();
//            }
//        }
//    }
    private void startNumberThread() {
        numberThread = new Thread(() -> {
            Random random = new Random();
            while (!Thread.interrupted()) {
                randomNumber = random.nextInt(900000) + 100000;
                System.out.println("Số ngẫu nhiên: " + randomNumber);

                try {
                    Thread.sleep(30000); // Sleep for 1 minute
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                    return;
                }
            }
        });
        numberThread.start();
        isRunning = true;
    }

    public void GuiMail() {
        try {
            Properties p = new Properties();
            p.put("mail.smtp.auth", "true");
            p.put("mail.smtp.starttls.enable", "true");
            p.put("mail.smtp.host", "smtp.gmail.com");
            p.put("mail.smtp.port", 587);

            String accountName = "dhuyclone2001@gmail.com";
            String accountPassword = "xolqvydetnilxcxy";
            Session s = Session.getInstance(p,
                    new javax.mail.Authenticator() {
                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication(accountName, accountPassword);
                }
            });
            String from = "dhuyclone2001@gmail.com";
            String to = txtEmail.getText();
            String subject = "Mã xác nhận";
            String body = "Mã xác nhận của bạn là: " + String.valueOf(randomNumber);
            Message msg = new MimeMessage(s);
            msg.setFrom(new InternetAddress(from));
            msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse(to));
            msg.setSubject(subject);
            msg.setText(body);
            Transport.send(msg);
            JOptionPane.showMessageDialog(null, "Mail was sent successfully", "Message",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Vui long nhap lai mail!");
            e.printStackTrace();
        }
    }

//    public boolean checkMa() {
//        if (txtMaXacNhan.getText().equals(String.valueOf(randomNumber))) {
//            System.out.println("true!");
//        } else {
//            System.out.println("false!");
//        }
//    }
    public boolean validateForm() {
//        if (txtMaAD.getText().isBlank() && txtHoTen.getText().isBlank() && txtSDT.getText().isBlank() && txtDiaChi.getText().isBlank()
//                && txtEmail.getText().isBlank() && txtMaTk.getText().isBlank() && txtUser.getText().isBlank() && txtPass.getText().isBlank() && txtMaXacNhan.getText().isBlank()) {
//            JOptionPane.showMessageDialog(this, "Chưa có thông tin !");
//            txtMaTk.requestFocus();
//            return false;
//        }
//        if (txtMaAD.getText().trim().equals("")) {
//            JOptionPane.showMessageDialog(this, "Chưa điền mã người dùng !");
//            txtMaAD.requestFocus();
//            return false;
//        }
        if (txtHoTen.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa điền tên người dùng !");
            txtHoTen.requestFocus();
            return false;
        }
        if (txtSDT.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập số điện thoại!");
            txtSDT.requestFocus();
            return false;
        }
        if (txtDiaChi.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập vào địa chỉ !");
            txtDiaChi.requestFocus();
            return false;
        }
        if (txtEmail.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập email !");
            txtEmail.requestFocus();
            return false;
        }
//        if (txtMaTk.getText().trim().equals("")) {
//            JOptionPane.showMessageDialog(this, "Chưa nhập mã TK !");
//            txtMaTk.requestFocus();
//            return false;
//        }

        if (txtUser.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập username !");
            txtUser.requestFocus();
            return false;
        }

        char[] passwordChars = txtPass.getPassword();
        String password = new String(passwordChars);
        if (password.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập password !");
            txtPass.requestFocus();
            return false;
        }
//        if (txtMaXacNhan.getText().trim().equals("")) {
//            JOptionPane.showMessageDialog(this, "Chưa nhập mã xác nhận !");
//            txtMaXacNhan.requestFocus();
//            return false;
//        }

        if (!txtMaXacNhan.getText().trim().equals(String.valueOf(randomNumber))) {
            JOptionPane.showMessageDialog(this, "Mã xác nhận sai !");
            txtMaXacNhan.requestFocus();
            return false;
        }

        String sdt = "^0+\\d*[0-9]{9}$";
        String email = "^[A-Za-z0-9._%+]+@[A-Za-z0-9.]+\\.[A-Za-z]{2,}$";
        if (txtSDT.getText().matches(sdt) == false) {
            JOptionPane.showMessageDialog(this, "SĐT sai định dạng !");
            txtSDT.requestFocus();
            return false;

        }
        if (txtEmail.getText().matches(email) == false) {
            JOptionPane.showMessageDialog(this, "Email sai định dạng !");
            txtEmail.requestFocus();
            return false;
        }
        return true;
    }

    public boolean validateMaXN() {
        if (txtHoTen.getText().isBlank() && txtSDT.getText().isBlank() && txtDiaChi.getText().isBlank()
                && txtEmail.getText().isBlank() && txtUser.getText().isBlank() && txtPass.getText().isBlank() && txtMaXacNhan.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Chưa có thông tin !");

            return false;
        }
//        if (txtMaAD.getText().trim().equals("")) {
//            JOptionPane.showMessageDialog(this, "Chưa điền mã người dùng !");
//            txtMaAD.requestFocus();
//            return false;
//        }
        if (txtHoTen.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa điền tên người dùng !");
            txtHoTen.requestFocus();
            return false;
        }
        if (txtSDT.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập số điện thoại!");
            txtSDT.requestFocus();
            return false;
        }
        if (txtDiaChi.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập vào địa chỉ !");
            txtDiaChi.requestFocus();
            return false;
        }
        if (txtEmail.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập email !");
            txtEmail.requestFocus();
            return false;
        }
//        if (txtMaTk.getText().trim().equals("")) {
//            JOptionPane.showMessageDialog(this, "Chưa nhập mã TK !");
//            txtMaTk.requestFocus();
//            return false;
//        }

        if (txtUser.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập username !");
            txtUser.requestFocus();
            return false;
        }

        char[] passwordChars = txtPass.getPassword();
        String password = new String(passwordChars);
        if (password.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập password !");
            txtPass.requestFocus();
            return false;
        }
//        if (txtMaXacNhan.getText().trim().equals("")) {
//            JOptionPane.showMessageDialog(this, "Chưa nhập mã xác nhận !");
//            txtMaXacNhan.requestFocus();
//            return false;
//        }

//        if (!txtMaXacNhan.getText().trim().equals(String.valueOf(randomNumber))) {
//            JOptionPane.showMessageDialog(this, "Mã xác nhận sai !");
//            txtMaXacNhan.requestFocus();
//            return false;
//        }
        String sdt = "^0+\\d*[0-9]{9}$";
        String email = "^[A-Za-z0-9._%+]+@[A-Za-z0-9.]+\\.[A-Za-z]{2,}$";
        if (txtSDT.getText().matches(sdt) == false) {
            JOptionPane.showMessageDialog(this, "SĐT sai định dạng !");
            txtSDT.requestFocus();
            return false;

        }
        if (txtEmail.getText().matches(email) == false) {
            JOptionPane.showMessageDialog(this, "Email sai định dạng !");
            txtEmail.requestFocus();
            return false;
        }
        return true;
    }

   public void startCountDown() {
        btnGuiMa.setEnabled(false);
        remainingSeconds = 30; // 2 minutes in seconds
        timer = new Timer(1000, (ActionEvent e) -> {
            if (remainingSeconds > 0) {
                int minutes = remainingSeconds / 60;
                int seconds = remainingSeconds % 60;
                txtThoiGian.setText("Time remaining: " + String.format("%02d:%02d", minutes, seconds));
                remainingSeconds--;
            } else if (remainingSeconds == -1) {
                txtThoiGian.setText("Mã xác nhận có hiệu lực trong 30s");
                timer.stop();
                btnGuiMa.setEnabled(true);
            } else {
                txtThoiGian.setText("Mã xác nhận hết hiệu lục vui lòng ấn gửi lại");
                timer.stop();
                btnGuiMa.setEnabled(true);
            }
        });
        timer.start();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DkUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DkUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DkUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DkUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DkUi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKi;
    private javax.swing.JButton btnGuiMa;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaXacNhan;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JLabel txtThoiGian;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables



}
