/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mylibsys.libsystem.ui;

import com.mylibsys.libsystem.dao.phieuMuonCTDao;
import com.mylibsys.libsystem.entity.phieuMuon;
import com.mylibsys.libsystem.entity.phieuMuonChiTiet;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kuteb
 */
public class lichSuXoaPmct extends javax.swing.JFrame {

    private DefaultTableModel tblModel;
    phieuMuonCTDao pmctd = new phieuMuonCTDao();
    private PropertyChangeSupport propertyChangeSupport;

    /**
     * Creates new form lichSuXoaPtraUi
     */
    public lichSuXoaPmct() {
        initComponents();
        inittables();
        fillDataTable();
        propertyChangeSupport = new PropertyChangeSupport(this);

    }

    public void inittables() {
        tblModel = new DefaultTableModel();
        String[] colum = new String[]{"Mã PMCT", "Mã Phiếu Mượn", "Mã Sách", "Số Lượng", "Tình Trạng"};
        tblModel.setColumnIdentifiers(colum);
        tblBangPhieuMuonChiTietXoa.setModel(tblModel);

    }
//    List<phieuMuon> list = new ArrayList<>();

    @Override
    public void addPropertyChangeListener(PropertyChangeListener listener) {
        propertyChangeSupport.addPropertyChangeListener(listener);
    }

    private void fireTableDataChangedEvent() {
        propertyChangeSupport.firePropertyChange("tableDataChanged", null, null);
    }

    public void fillDataTable() {
//        list = new phieuMuonDao().selectBySql();
        for (phieuMuonChiTiet pmct : new phieuMuonCTDao().selectBySqlXoa()) {
            tblModel.addRow(new String[]{pmct.getMaPmct(), pmct.getMaPM(), pmct.getMaSach(), String.valueOf(pmct.getSoLuong()), pmct.getTinhTrang()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        txtTim = new javax.swing.JTextField();
        btnReset1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBangPhieuMuonChiTietXoa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 549));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Lịch Sử Xoá Phiếu Mượn Chi Tiết");

        jButton1.setText("Khôi Phục");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnReset1.setText("Reset Table");
        btnReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset1ActionPerformed(evt);
            }
        });

        tblBangPhieuMuonChiTietXoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblBangPhieuMuonChiTietXoa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jButton1)
                .addGap(30, 30, 30)
                .addComponent(btnReset1)
                .addGap(33, 33, 33)
                .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnTimKiem)
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnTimKiem)
                    .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset1ActionPerformed
        tblModel.setRowCount(0);
        fillDataTable();
    }//GEN-LAST:event_btnReset1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int a = tblBangPhieuMuonChiTietXoa.getSelectedRow();
        System.out.println("a la" + a);
        if (a == -1) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn dòng khôi phục !");
            return;
        } else {
            System.out.println(pmctd.restore((String) tblModel.getValueAt(a, 0)));
            tblModel.setRowCount(0);
            fillDataTable();
            fireTableDataChangedEvent();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        if ("".equals(txtTim.getText())) {
            JOptionPane.showMessageDialog(this, "ô tìm kiếm đang trống");
            return;
        }
        if (timKiem() != -1) {
            JOptionPane.showMessageDialog(this, "Đã tìm thấy");
            tblBangPhieuMuonChiTietXoa.setRowSelectionInterval(timKiem(), timKiem());
        } else {
            JOptionPane.showMessageDialog(this, "Không tồn tại");

        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lichSuXoaPmct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lichSuXoaPmct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lichSuXoaPmct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lichSuXoaPmct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lichSuXoaPmct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset1;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBangPhieuMuonChiTietXoa;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables
public int timKiem() {
        String searchText = txtTim.getText();
        List<phieuMuonChiTiet> resultList = pmctd.selectBySqlXoa(); // Thay SomeObjectType bằng kiểu đối tượng mà pmd.selectBySqlXoa() trả về

        for (int i = 0; i < resultList.size(); i++) {
            phieuMuonChiTiet item = resultList.get(i);
            if (searchText.equals(item.getMaPM())) {
                return i;
            }
        }

        return -1; // Trả về -1 khi không tìm thấy kết quả
    }

}
