/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mylibsys.libsystem.ui;

import com.mylibsys.libsystem.dao.UserDao;
import static com.mylibsys.libsystem.dao.UserDao.maTk;
import com.mylibsys.libsystem.entity.NguoiDung;
import static com.mylibsys.libsystem.utils.dateFormart.formatDate;
import static com.mylibsys.libsystem.utils.loginGoogle.gmail;
import static com.mylibsys.libsystem.utils.sqlSeverConnectMayChu.layKetNoi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author kuteb
 */
public class thongTinND extends javax.swing.JPanel {

    UserDao usd = new UserDao();
    Connection conn = null;
    PreparedStatement sttm = null;
JFrame fr = new JFrame();
    /**
     * Creates new form thongTinND
     */
    public thongTinND() {
        initComponents();
        getTT();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnCapNhat = new javax.swing.JButton();
        txtSDT = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtPhat = new javax.swing.JTextField();
        btnDoiMK = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(850, 550));
        setMinimumSize(new java.awt.Dimension(850, 550));
        setPreferredSize(new java.awt.Dimension(850, 550));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Họ tên :");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("SĐT : ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Địa chỉ :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Ngày lập tài khoản :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Số tiền đã đóng phạt :");

        btnCapNhat.setBackground(new java.awt.Color(255, 255, 102));
        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCapNhat.setText("Cập nhật thông tin");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });

        txtDate.setEnabled(false);
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });

        txtDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChiActionPerformed(evt);
            }
        });

        txtPhat.setEnabled(false);
        txtPhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhatActionPerformed(evt);
            }
        });

        btnDoiMK.setBackground(new java.awt.Color(255, 255, 102));
        btnDoiMK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDoiMK.setText("Đổi mật khẩu");
        btnDoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPhat, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCapNhat)
                                .addGap(62, 62, 62)
                                .addComponent(btnDoiMK)
                                .addGap(96, 96, 96)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhat, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDoiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Thông tin cá nhân");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
            .addGroup(layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel7)
                .addGap(55, 55, 55)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    //code

    public int fillTTcaNhan(String MaTK) {
        try {
            String sql = "EXEC fillttByMatk @MaTK = ?";
            conn = layKetNoi();
            sttm = conn.prepareStatement(sql);
            sttm.setString(1, MaTK);
            ResultSet rs = sttm.executeQuery();

            while (rs.next()) {
                txtName.setText(rs.getString(1));
                txtSDT.setText(rs.getString(2));
                txtDiaChi.setText(rs.getString(3));
                txtDate.setText(formatDate(rs.getString(4)));
            }
        } catch (Exception e) {
            System.out.println("Lỗi !" + e.toString());
        }
        return -1;
    }

    public int fillTTcaNhan2(String gmail) {
        try {
            String sql = "EXEC fillttByGmail @gmail = ?";
            conn = layKetNoi();
            sttm = conn.prepareStatement(sql);
            sttm.setString(1, gmail);
            ResultSet rs = sttm.executeQuery();

            while (rs.next()) {
                txtName.setText(rs.getString(1));
                txtSDT.setText(rs.getString(2));
                txtDiaChi.setText(rs.getString(3));
                txtDate.setText(formatDate(rs.getString(4)));
            }
        } catch (Exception e) {
            System.out.println("Lỗi !" + e.toString());
        }
        return -1;
    }

    public int qurrey(String MaTK) {
        try {
            String sql = "EXEC GetTotalPenaltyByMaTK @MaTK = ?;";
            conn = layKetNoi();
            sttm = conn.prepareStatement(sql);
            sttm.setString(1, MaTK);
            ResultSet rs = sttm.executeQuery();
            while (rs.next()) {
                txtPhat.setText(String.valueOf(rs.getDouble(1)));
            }
        } catch (Exception e) {
            System.out.println("Lỗi !" + e.toString());
        }
        return -1;
    }

    public int qurrey2(String gmail) {
        try {
            String sql = "EXEC GetTotalPenaltyByGmail @gmail = ?;";
            conn = layKetNoi();
            sttm = conn.prepareStatement(sql);
            sttm.setString(1, gmail);
            ResultSet rs = sttm.executeQuery();
            while (rs.next()) {
                txtPhat.setText(String.valueOf(rs.getDouble(1)));
            }
        } catch (Exception e) {
            System.out.println("Lỗi !" + e.toString());
        }
        return -1;
    }

    public void getTT() {
        if (gmail == null) {
            fillTTcaNhan(maTk);
            qurrey(maTk);
        } else {
            fillTTcaNhan2(gmail);
            qurrey2(gmail);
        }
    }

    public int updateMaTK(NguoiDung nd) {
        try {
            String sql = "update NguoiDung set TenND=?, SoDienThoai=?, DiaChi=?  where MaTK = ? and Enable = 'true'";
            conn = layKetNoi();
            sttm = conn.prepareStatement(sql);
            sttm.setString(1, nd.getTenND());
            sttm.setString(2, nd.getSdt());
            sttm.setString(3, nd.getDiaChi());
            sttm.setString(4, maTk);
            if (sttm.executeUpdate() > 0) {
                System.out.println("Cập nhật thành công !");
                return 1;
            }
        } catch (Exception e) {
            System.out.println("Lỗi!" + e.toString());
        }
        return -1;
    }

    public int updateGmail(NguoiDung nd) {
        try {
            String sql = "update NguoiDung set TenND=?, SoDienThoai=?, DiaChi=?"
                    + " where Email = '" + gmail + "'" + " and Enable = 'true'";
            conn = layKetNoi();
            sttm = conn.prepareStatement(sql);
            sttm.setString(1, nd.getTenND());
            sttm.setString(2, nd.getSdt());
            sttm.setString(3, nd.getDiaChi());

            if (sttm.executeUpdate() > 0) {
                System.out.println("Cập nhật thành công !");
                return 1;
            }
        } catch (Exception e) {
            System.out.println("Lỗi!" + e.toString());
        }
        return -1;
    }

    //code
    public NguoiDung getModel() {
        NguoiDung nd = new NguoiDung();
        nd.setTenND(txtName.getText());
        nd.setSdt(txtSDT.getText());
        nd.setDiaChi(txtDiaChi.getText());
        return nd;
    }

    public boolean validateForm() {
        if (txtName.getText().isBlank() && txtSDT.getText().isBlank() && txtDiaChi.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Chưa có thông tin !");
            return false;
        }

        if (txtName.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa điền tên người dùng !");
            txtName.requestFocus();
            return false;
        }
        if (txtSDT.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập số điện thoại!");
            txtSDT.requestFocus();
            return false;
        }
        if (txtDiaChi.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập vào địa chỉ !");
            txtDiaChi.requestFocus();
            return false;
        }

        String sdt = "^0+\\d*[0-9]{9}$";

        if (txtSDT.getText().matches(sdt) == false) {
            JOptionPane.showMessageDialog(this, "SĐT sai định dạng !");
            txtSDT.requestFocus();
            return false;
        }
        return true;
    }

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        if (validateForm()) {
            NguoiDung nd = getModel();

            try {
                int result = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn cập nhật người dùng này", "Xác nhận", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (result == JOptionPane.YES_OPTION) {
                    if (gmail != null) {
                        if (updateGmail(nd) > 0) {
                            JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
                        }
                    } 
                    
                    if(gmail==null){

                        if (updateMaTK(nd) > 0) {
                            JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
                            System.out.println("oke");
                        }

                    }

                } else if (result == JOptionPane.NO_OPTION) {
                    JOptionPane.showMessageDialog(this, "Bạn chọn không!");

                } else {
                    JOptionPane.showMessageDialog(this, "không chọn!");

                }
            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void txtDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChiActionPerformed

    private void txtPhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhatActionPerformed

    private void btnDoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMKActionPerformed
        // TODO add your handling code here:
        
        JPanel jp = new DoiMatKhauCaNhanUi();
        fr.add(jp);
        fr.setSize(900, 600);
        fr.setLocationRelativeTo(null);
        fr.setVisible(true);
    }//GEN-LAST:event_btnDoiMKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnDoiMK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhat;
    private javax.swing.JTextField txtSDT;
    // End of variables declaration//GEN-END:variables
}
